[package]
name = "orx-split-vec"
version = "3.3.0"
edition = "2021"
authors = ["orxfun <orx.ugur.arikan@gmail.com>"]
description = "An efficient constant access time vector with dynamic capacity and pinned elements."
license = "MIT"
repository = "https://github.com/orxfun/orx-split-vec/"
keywords = ["vec", "array", "split", "fragments", "pinned"]
categories = ["data-structures", "rust-patterns"]

[dependencies]
orx-pseudo-default = "1.2"
orx-pinned-vec = "3.3"

[[bench]]
name = "serial_access"
harness = false

[dev-dependencies]
criterion = { version = "0.5", default-features = false }
rand = { version = "0.8", default-features = false }
rand_chacha = { version = "0.3", default-features = false }
test-case = "3.3.1"
wasm-bindgen = "0.2"
wasm-bindgen-test = "0.3"
