[package]
name = "orx-split-vec"
version = "3.15.0"
edition = "2021"
authors = ["orxfun <orx.ugur.arikan@gmail.com>"]
description = "An efficient dynamic capacity vector with pinned element guarantees."
license = "MIT OR Apache-2.0"
repository = "https://github.com/orxfun/orx-split-vec/"
keywords = ["vec", "array", "split", "fragments", "pinned"]
categories = ["data-structures", "rust-patterns", "no-std"]

[dependencies]
orx-iterable = { version = "1.2.0", default-features = false }
orx-pseudo-default = { version = "2.0.0", default-features = false }
orx-pinned-vec = "3.15"
orx-concurrent-iter = { path = "../orx-concurrent-iter" }

[[bench]]
name = "serial_access"
harness = false

[dev-dependencies]
criterion = { version = "0.5", default-features = false }
rand = { version = "0.9", default-features = false }
rand_chacha = { version = "0.9", default-features = false }
test-case = "3.3.1"
wasm-bindgen = "0.2"
wasm-bindgen-test = "0.3"
